### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by NetOperatorWibby** [curveball/cors#4]
This module is not on npm so the README is inaccurate. Thankfully this package is really just one file so I could include it in my project and use it.

Also, seems like this module should be placed before the body parser. The order in my project is:

- `accesslog`
- `problem`
- `cors`
- `bodyparser`
- routes

**Comment by juhangsin** [comment]
Hey @NetOperatorWibby, I just saw this issue. Sorry about that. Now it's a npm pkg.
https://www.npmjs.com/package/@curveball/cors
